// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpgIsaIGreC5WvsoxVnguHJ-pxjcazzw',
    appId: '1:548284647952:web:4c47463cef1c5e509e1895',
    messagingSenderId: '548284647952',
    projectId: 'pranamas-ffcd0',
    authDomain: 'pranamas-ffcd0.firebaseapp.com',
    storageBucket: 'pranamas-ffcd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAP7T3J53sA-CAOEMbDmk0JT0qhhClQV4',
    appId: '1:548284647952:android:5c9c14886097ba6b9e1895',
    messagingSenderId: '548284647952',
    projectId: 'pranamas-ffcd0',
    storageBucket: 'pranamas-ffcd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJVNC57NpAB9u7sXXnDzigG9qm7ZJxMZA',
    appId: '1:548284647952:ios:ea212ae29f0d692f9e1895',
    messagingSenderId: '548284647952',
    projectId: 'pranamas-ffcd0',
    storageBucket: 'pranamas-ffcd0.appspot.com',
    iosBundleId: 'com.example.pranamas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJVNC57NpAB9u7sXXnDzigG9qm7ZJxMZA',
    appId: '1:548284647952:ios:ea212ae29f0d692f9e1895',
    messagingSenderId: '548284647952',
    projectId: 'pranamas-ffcd0',
    storageBucket: 'pranamas-ffcd0.appspot.com',
    iosBundleId: 'com.example.pranamas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGpgIsaIGreC5WvsoxVnguHJ-pxjcazzw',
    appId: '1:548284647952:web:d5a45cdd4a589f9b9e1895',
    messagingSenderId: '548284647952',
    projectId: 'pranamas-ffcd0',
    authDomain: 'pranamas-ffcd0.firebaseapp.com',
    storageBucket: 'pranamas-ffcd0.appspot.com',
  );
}
