import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:iconsax/iconsax.dart';
import 'package:pranamas/controllers/sign_up_controller.dart';
import 'package:pranamas/models/agama_model.dart';
import 'package:pranamas/repository/agama_repo.dart';
import '../users/network_manager.dart';

class AgamaController extends GetxController {
  RxList<AgamaModel> agamaModel = <AgamaModel>[].obs;
  final isLoadingAgama = RxBool(false);
  final agama = ''.obs;
  final errorMessage = ''.obs;
  final agamaRepo = Get.put(AgamaRepository());
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  @override
  void onInit() {
    super.onInit();
    fetchDataAgama();
  }

  bool validateAgama() {
    if (agama.value.isEmpty) {
      errorMessage.value = "Please select a religion";
      return false;
    }
    errorMessage.value = "";
    return true;
  }

  Future<String?> sendAgamaContent() async {
    if (!await checkConnectivityAndShowDialog()) {
      return null;
    }
    if (!validateAgama()) {
      hideDialog();
      return null;
    }
    try {
      // Create new model without ID, as it will be generated by Firestore
      final newdataAgama = AgamaModel(agama: agama.value, agamaId: '');
      final docId = await agamaRepo.saveAgamaContent(newdataAgama);
      // agamaRepo.saveAgamaContent(newdataAgama);
      // Update model with ID from Firestore
      newdataAgama.agamaId = docId; // harusnya data user di tambahin kaya gini
      agamaModel.add(newdataAgama);
      agama.value = '';
      update();
      showSuccessSnackbar(
          'Congratulations', 'Your Agama content has been created!');
    } catch (e) {
      showErrorSnackbar('Oh Snap!', e.toString());
    }
    hideDialog();
    return null;
  }

  Future<void> fetchDataAgama() async {
    isLoadingAgama.value = true;
    try {
      final dataUsers = await agamaRepo.fetchDataAgama();
      agamaModel.assignAll(dataUsers);
    } catch (e) {
      agamaModel.assignAll([]);
      showErrorSnackbar('Data Fetch Error', 'Failed to fetch data: $e');
    } finally {
      isLoadingAgama.value = false;
    }
  }

  Future<void> deleteAgamaUser(AgamaModel agama) async {
    try {
      await agamaRepo.deleteAgama(agama.agamaId);
      agamaModel.remove(agama);
      update();
    } catch (e) {
      showErrorSnackbar('Delete Error', 'Failed to delete agama: $e');
    }
  }

  Future<void> editAgamaData(AgamaModel updatedData) async {
    try {
      print(
          "Updating document: $updatedData with data: ${updatedData.toJson()}");
      QuerySnapshot querySnapshot = await _db
          .collection('agamaMaster')
          .where('agama', isEqualTo: updatedData.agama)
          .get();

      if (querySnapshot.docs.isNotEmpty) {
        await querySnapshot.docs.first.reference.update(updatedData.toMap());
      } else {
        throw Exception('No user found with userId: ${updatedData.agamaId}');
      }
      print("Document updated successfully");

      Get.snackbar(
        'Success',
        'Agama data updated successfully',
        backgroundColor: Colors.green,
        colorText: Colors.white,
        icon: const Icon(Iconsax.edit, color: Colors.white),
      );
    } catch (e) {
      print("Error updating document: $e");
      Get.snackbar(
        'Update Error',
        'Failed to update agama data: ${e.toString()}',
        backgroundColor: Colors.red.shade600,
        colorText: Colors.white,
        icon: const Icon(Iconsax.warning_2, color: Colors.white),
      );
    }
  }

  void showSuccessSnackbar(String title, String message) {
    Get.snackbar(title, message,
        backgroundColor: Colors.green, colorText: Colors.white);
  }

  void showErrorSnackbar(String title, String message) {
    Get.snackbar(title, message,
        backgroundColor: Colors.red.shade600, colorText: Colors.white);
  }

  Future<bool> checkConnectivityAndShowDialog() async {
    showDialog(
      context: Get.overlayContext!,
      barrierDismissible: false,
      builder: (_) => const PopScope(
        canPop: false,
        child: AnimationLoader(
          text: 'Processing...',
          animation: 'assets/animations/141594-animation-of-docer.json',
          showAction: false,
        ),
      ),
    );
    final isConnected = await NetworkManager.instance.isConnected();
    if (!isConnected) {
      hideDialog();
      showErrorSnackbar(
          'Network Error', 'Please check your internet connection');
      return false;
    }
    return true;
  }

  void hideDialog() {
    Navigator.of(Get.overlayContext!).pop();
  }
}
